---
title: "esplorando_base_datos"
author: "RMMD"
date: "2025-09-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)   # Para leer archivos CSV
library(readxl)  # Para leer archivos Excel
library(dplyr)   # Para la función glimpse()
```

Este documento R Markdown carga varios archivos de datos y luego utiliza glimpse() para mostrar un resumen rápido de la estructura de cada uno, incluyendo el número de filas y columnas, los nombres de las columnas y sus tipos de datos, y las primeras entradas.


```{r glimpse-secciones-sd}
secciones_sd <- read_csv("data/datos_por_seccion_NUEVO_LEON.csv", show_col_types = FALSE)
glimpse(secciones_sd)
```
## 2. censales
```{r glimpse-censales}
censales <- read_csv("data/estadisticas_censales_nuevoleon.csv", show_col_types = FALSE)
glimpse(censales)
```
## 3. cant_votos_nl
```{r glimpse-cant-votos-nl}
cant_votos_nl <- read_csv("data/cant_votos_nl.csv", show_col_types = FALSE)
glimpse(cant_votos_nl)

```
```{r}
combinaciones_unicas_eleccion_año <- cant_votos_nl %>%
  distinct(eleccion, año)
print(combinaciones_unicas_eleccion_año)
```




## 4. base_ganadores
```{r glimpse-base-ganadores}
base_ganadores <- read_csv("data/datos_ganadores_NUEVO_LEON.csv", show_col_types = FALSE)
glimpse(base_ganadores)
```


















